"""removed Dob

Revision ID: 632fef610f39
Revises: 2165929f3dd3
Create Date: 2024-12-02 20:40:19.507623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632fef610f39'
down_revision = '2165929f3dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
