"""empty message

Revision ID: a7483a31d16c
Revises: 
Create Date: 2024-12-02 01:49:41.442730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7483a31d16c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_comment_post_id'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_comment_user_id'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_likes_post_id'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_likes_user_id'),
        sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shares', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))
        # Specify a name for the foreign key constraint if there are additional foreign keys
        batch_op.create_foreign_key('fk_post_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_user_id', type_='foreignkey')
        batch_op.drop_column('comments_count')
        batch_op.drop_column('shares')

    op.drop_table('likes')
    op.drop_table('comment')
    # ### end Alembic commands ###